### ISSUE TITLE
v.1.0.8 does not work with v.1.0.6 templates.

### ISSUE THREAD

**Issue by jamessandison** [TuomoKu/SPX-GC#15]
I'm not sure if something has changed between v.1.0.8 and v.1.0.6, but templates that were working with v.1.0.6 are not working in v.1.0.8.

The CasparCG server says that `play is not defined` and `update is not defined` when playing the templates, and `[webcg-framework] version 2.6.0` does not get printed in the console for my template, but does in v.1.0.6.

I think this may have something to do with the webcg-framework not loading? Interestingly, if I use the CasparCG Client, the template works fine.

**Comment by TuomoKu** [comment]
Yes, there is an issue with 1.0.8 with a "non-local" CasparCG playout. (Some dev environment related code was accidentally published).

This is fixed in 1.0.9, which will be released today.

**Comment by jamessandison** [comment]
Thanks @TuomoKu!! I will hopefully have a bit more of a look at the source code and if I can, I'll try and contribute! Love the work you are doing on this!

**Comment by TuomoKu** [comment]
Fixed in 1.0.9.

**Comment by jamessandison** [comment]
@TuomoKu I'm still having the same issue in 1.0.9 - I can resolve the issue by copying the template into the SPX-GC which is fine, but it looks like something is triggered differently - I will try and do a bit more digging into the problem too

**Comment by TuomoKu** [comment]
I should have given a more detailed answer, sorry for that.

**Sympthom**
If CasparCG reports `play is not defined` and `update is not defined` it **can mean** that there is no template found from the given template path and therefor no javascript functions `play` and `update` can be found. (Which is "true", but the actual problem is there is no template to begin with, so the errormessage given by CCG may be misleading...)

**Nasty bug in 1.0.8**
Accidentally 1.0.8 sent CasparCG a _template load command_ with url "localhost:" which is obviously wrong when CasparCG and SPX-GC are running on different hosts.

**Fix in 1.0.9 and a new configuration option**
In 1.0.9 there is now a `general.templatesource` parameter in config.json.  The default value `spxgc-ip-address` uses the IP address of SPX-GC by default for loading templates in CasparCG. But since the IP address automatically detected may be the _internal_ IP (on VM instances, for example) there is now an option to overwrite it with any http-address of the SPX-GC server. The third option is to use a value `casparcg-template-path` which changes the template load command to obay the template-path value of the target CasparCG server (and file-protocol).

This info is also added to the [README.md](https://github.com/TuomoKu/SPX-GC#config).

Hope this helps.
